<?php
/**
 * (c) Vadim Pavlov 2020 - 2026
 * update_psl.php - Refresh the bundled Public Suffix List used by the Research
 * RDAP tool to reduce a hostname to its registrable domain.
 *
 * Downloads https://publicsuffix.org/list/public_suffix_list.dat and writes a
 * normalized copy to www/rpi_admin/data/public_suffix_list.dat containing:
 *   - the ICANN section only. The PRIVATE section describes delegated
 *     sub-namespaces (github.io, blogspot.com, s3.amazonaws.com, ...). For RDAP
 *     the question is "which name is registered with a registry", and that is
 *     github.io, not a user's project under it - so private rules must not be
 *     applied.
 *   - rules only, comments and blank lines stripped.
 *   - ASCII (punycode) labels, so the appliance needs no intl extension at
 *     runtime to match a punycode target against a Unicode rule.
 *
 * Usage: php scripts/update_psl.php [--dry-run]
 *
 * Requires PHP with intl (idn_to_ascii) - only on the machine running this
 * script, not on the appliance.
 */

const PSL_URL = 'https://publicsuffix.org/list/public_suffix_list.dat';

$dryRun = in_array('--dry-run', $argv, true);
$outFile = dirname(__DIR__) . '/www/rpi_admin/data/public_suffix_list.dat';

fwrite(STDERR, "Fetching " . PSL_URL . " ...\n");
$ctx = stream_context_create(['http' => ['timeout' => 60, 'user_agent' => 'RpiDNS-PSL-Updater']]);
$raw = @file_get_contents(PSL_URL, false, $ctx);
if ($raw === false || strlen($raw) < 50000) {
    fwrite(STDERR, "ERROR: download failed or suspiciously small.\n");
    exit(1);
}

// Keep the ICANN section only.
$start = strpos($raw, '// ===BEGIN ICANN DOMAINS===');
$end = strpos($raw, '// ===END ICANN DOMAINS===');
if ($start === false || $end === false || $end <= $start) {
    fwrite(STDERR, "ERROR: ICANN section markers not found; the list format changed.\n");
    exit(1);
}
$section = substr($raw, $start, $end - $start);

$hasIdn = function_exists('idn_to_ascii');
$rules = [];
$skipped = [];
// Explicit line separators, NOT \R: without the /u modifier \R also matches the
// bare byte 0x85, which occurs inside UTF-8 sequences (公 is E5 85 AC), and
// would split IDN rules mid-character.
foreach (preg_split('/\r\n|\r|\n/', $section) as $line) {
    $line = trim($line);
    if ($line === '' || strpos($line, '//') === 0) {
        continue;
    }

    // A rule may carry '!' (exception) or '*' labels; convert only the labels.
    $bang = '';
    if ($line[0] === '!') {
        $bang = '!';
        $line = substr($line, 1);
    }

    $labels = explode('.', $line);
    $ascii = [];
    $ok = true;
    foreach ($labels as $label) {
        if ($label === '*' || preg_match('/^[A-Za-z0-9-]+$/', $label)) {
            $ascii[] = strtolower($label);
            continue;
        }
        if (!$hasIdn) { $ok = false; break; }
        $converted = idn_to_ascii($label, IDNA_DEFAULT, INTL_IDNA_VARIANT_UTS46);
        if ($converted === false || $converted === '') { $ok = false; break; }
        $ascii[] = strtolower($converted);
    }
    if (!$ok) {
        $skipped[] = $bang . $line;
        continue;
    }
    $rules[] = $bang . implode('.', $ascii);
}

if (count($rules) < 5000) {
    fwrite(STDERR, "ERROR: only " . count($rules) . " rules parsed; refusing to write.\n");
    exit(1);
}
if (count($skipped) > 0) {
    // Refuse to ship a partial list: a missing rule silently yields the wrong
    // registrable domain for every name under that suffix.
    fwrite(STDERR, "ERROR: " . count($skipped) . " rule(s) could not be converted to ASCII"
        . ($hasIdn ? "" : " (no intl extension on this machine)") . ":\n");
    foreach (array_slice($skipped, 0, 10) as $s) { fwrite(STDERR, "  $s\n"); }
    exit(1);
}

$header = "// Public Suffix List - ICANN section only, normalized to ASCII (punycode).\n"
    . "// Source: " . PSL_URL . "\n"
    . "// Retrieved: " . gmdate('Y-m-d') . "\n"
    . "// Generated by scripts/update_psl.php - do not edit by hand.\n"
    . "// Consumed by www/rpi_admin/PublicSuffix.php (Research RDAP target reduction).\n";

$out = $header . implode("\n", $rules) . "\n";
fwrite(STDERR, count($rules) . " rules, " . strlen($out) . " bytes.\n");

if ($dryRun) {
    fwrite(STDERR, "--dry-run: nothing written.\n");
    exit(0);
}
if (!is_dir(dirname($outFile)) && !@mkdir(dirname($outFile), 0755, true)) {
    fwrite(STDERR, "ERROR: cannot create " . dirname($outFile) . "\n");
    exit(1);
}
if (@file_put_contents($outFile, $out) === false) {
    fwrite(STDERR, "ERROR: cannot write $outFile\n");
    exit(1);
}
fwrite(STDERR, "Wrote $outFile\n");
